d /var/lib/patent-search-prometheus 0750 patent-search-prometheus patent-search-prometheus -
d /etc/patent-search-prometheus 0750 root patent-search-prometheus -
d /etc/patent-search-prometheus/rules 0750 root patent-search-prometheus -
d /etc/patent-search-prometheus/targets 0750 root patent-search-prometheus -
