"""Shared hard timing limits for the FastAPI, metrics, and MCP processes."""

MAX_RUNTIME_OPENSEARCH_TIMEOUT_SECONDS = 240
MAX_RUNTIME_REQUEST_DEADLINE_SECONDS = 240
DURATION_OVERSHOOT_BUCKET_SECONDS = 300
MCP_BACKEND_TIMEOUT_MARGIN_SECONDS = 5
MIN_MCP_BACKEND_TIMEOUT_SECONDS = (
    MAX_RUNTIME_REQUEST_DEADLINE_SECONDS + MCP_BACKEND_TIMEOUT_MARGIN_SECONDS
)
